### PR TITLE
Shrink storage

### PR DESCRIPTION
**Pull request by deads2k**
This pays off some debt by eliminating duplicated functionality we created on the path to generic storage.

/hold  requires the finalization of our migration

### CODE REVIEW

**Comment by raelga** [comment]
/hold

**Holding pending reconciliation with #5710** — these two PRs have a semantic merge conflict that breaks the batched `e2e-parallel` lane.

Both recent batch runs that paired this PR with #5710 failed fast (~23m), never reaching e2e because the `aro-hcp-backend` image fails to **compile**:

- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/batch/pull-ci-Azure-ARO-HCP-main-e2e-parallel/2067856128229773312
- https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/batch/pull-ci-Azure-ARO-HCP-main-e2e-parallel/2067856816057880576

```
backend/pkg/controllers/cosmos_migration.go:211:59: cannot use clusterCRUD.Controllers(...)
  (ResourceCRUD[Controller, *Controller]) as ResourceCRUD[Controller] value ... need type assertion
backend/pkg/controllers/cosmos_migration.go:565:118: undefined: database.ManagementClusterContentCRUD
make: *** [Makefile:33: aro-hcp-backend] Error 1
```

**Why:** this PR ("Shrink storage") changes `internal/database` so that `ResourceCRUD` becomes two-type-param `ResourceCRUD[T, *T]` and removes the `ManagementClusterContentCRUD` interface. #5710 ("add Cosmos DB migration controller") adds `cosmos_migration.go`, which is written against the old single-param `ResourceCRUD[Controller]` and references the now-deleted `database.ManagementClusterContentCRUD`.

Each PR builds against `main` individually, but any batch combining both fails at backend compile — taking down the unrelated PRs sharing the batch.

#5710 is already in a healthy batch and this just restarted the E2E dance. This is why the hold has been put in this one.

Screenshot 2026-06-19 at 09 15 13

**Comment by raelga** [comment]
/hold cancel

Releasing this hold — it was misdirected. The backend build failures in the e2e-parallel batches are caused by #5710 not compiling against current main (the #5449 partition-key/CRUD refactor that already merged), not by this PR. Moving the hold to #5710.
